//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by the program.
// Executable version: 4.0.30319.42000
//
// Changes to this file may cause incorrect operation and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LPStudio.Properties {
    using System;
    
    
    /// <summary>
	/// A strongly typed resource class for looking up localized strings, etc.
	/// </summary>
	// This class was generated automatically by the StronglyTypedResourceBuilder class
	// using a tool like ResGen or Visual Studio.
	// To add or remove a member, edit the .ResX file and run ResGen again
	// with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
		/// Returns the cached ResourceManager instance used by this class.
		/// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LPStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
		/// Overwrites the current thread's CurrentUICulture property for all
		/// resource accesses using this strongly typed resource class.
		/// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap batteryImage32x32 {
            get {
                object obj = ResourceManager.GetObject("batteryImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap calibrationImage32x32 {
            get {
                object obj = ResourceManager.GetObject("calibrationImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap connectionPanelImage32x32 {
            get {
                object obj = ResourceManager.GetObject("connectionPanelImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap consoleImage32x32 {
            get {
                object obj = ResourceManager.GetObject("consoleImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap cubeG_codeImage32x32 {
            get {
                object obj = ResourceManager.GetObject("cubeG-codeImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap deviceImage32x32 {
            get {
                object obj = ResourceManager.GetObject("deviceImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap downArrowImage32x32 {
            get {
                object obj = ResourceManager.GetObject("downArrowImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap homeImage16x16 {
            get {
                object obj = ResourceManager.GetObject("homeImage16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap homeImage32x32 {
            get {
                object obj = ResourceManager.GetObject("homeImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap leftArrowImage32x32 {
            get {
                object obj = ResourceManager.GetObject("leftArrowImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap maximizeWindowImage32x32 {
            get {
                object obj = ResourceManager.GetObject("maximizeWindowImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap minimizeWindowImage32x32 {
            get {
                object obj = ResourceManager.GetObject("minimizeWindowImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap prepareImag {
            get {
                object obj = ResourceManager.GetObject("prepareImag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap prepareImag32x32 {
            get {
                object obj = ResourceManager.GetObject("prepareImag32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap previewIcon {
            get {
                object obj = ResourceManager.GetObject("previewIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap rejectWindow {
            get {
                object obj = ResourceManager.GetObject("rejectWindow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap rejectWindow1 {
            get {
                object obj = ResourceManager.GetObject("rejectWindow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap rejectWindow32x32 {
            get {
                object obj = ResourceManager.GetObject("rejectWindow32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap restoreImage32x32 {
            get {
                object obj = ResourceManager.GetObject("restoreImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap rigthArrowImage32x32 {
            get {
                object obj = ResourceManager.GetObject("rigthArrowImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap toolImage32x32 {
            get {
                object obj = ResourceManager.GetObject("toolImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
		/// Search for a localized resource of type System.Drawing.Bitmap.
		/// </summary>
        internal static System.Drawing.Bitmap upArrowImage32x32 {
            get {
                object obj = ResourceManager.GetObject("upArrowImage32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
