#include "GCodeWriter.h"

#include <iomanip>
#include <utility>

GCodeWriter::GCodeWriter(GCodeConfig writerConfig) : config(std::move(writerConfig)) 
{
}

double GCodeWriter::toMm(int pixel) const {
	if (config.pixelsPerMm <= 0.0) {
		return static_cast<double>(pixel);
	}

	return static_cast<double>(pixel) / config.pixelsPerMm;
}

void GCodeWriter::writeHeader(std::ofstream& out) const {
	out << "; Generated by MotionCompiler\n";
	out << "; Basic image-to-G-Code compiler\n";

	out << "G21\n";
	out << "G90\n";

	out << std::fixed << std::setprecision(2);

	out << "G0 Z" << config.liftHeightMm << " F" << config.travelSpeedMmMin << "\n";
}

void GCodeWriter::writeFooter(std::ofstream& out) const {
	if (config.returnToOrigin) {
		out << "G0 Z" << config.liftHeightMm << " F" << config.travelSpeedMmMin << "\n";
	
		out << "G0 X" << config.startX << " Y" << config.startY << " F" << config.travelSpeedMmMin << "\n";
	}

	out << "M2\n";
}

void GCodeWriter::writePenUp(std::ofstream& out) const {
	out << "G0 Z" << config.liftHeightMm << " F" << config.travelSpeedMmMin << "\n";
}

void GCodeWriter::writePenDown(std::ofstream& out) const {
	out << "G1 Z0 F" << config.printSpeedMmMin << "\n";
}

void GCodeWriter::writeTravel(std::ofstream& out, const Point& target) const {
	out << "G0 X" << toMm(target.x) << " Y" << toMm(target.y) << " F" << config.travelSpeedMmMin << "\n";
}

void GCodeWriter::writeMove(std::ofstream& out, const Point& target) const {
	out << "G1 X" << toMm(target.x) << " Y" << toMm(target.y) << " F" << config.printSpeedMmMin << "\n";
}

bool GCodeWriter::write(const ImageProfile& profile, const std::string& filename) const {
	std::ofstream out(filename, std::ios::out | std::ios::trunc);

	if (!out.is_open()) {
		return false;
	}

	writeHeader(out);

	for (const auto& contour : profile.contours) {
		if (contour.points.empty()) {
			continue;
		}

		// между независимыми контурами всегда поднимаем голову
		// позже можно будет сделать отдельный режим travel moves
		writePenUp(out);

		writeTravel(out, contour.points.front());

		writePenDown(out);

		for (size_t i = 1; i < contour.points.size(); ++i) {
			writeMove(out, contour.points[i]);
		}

		// для замкнутого контура явно возвращаемся в начало
		if (contour.closed && contour.points.size() >= 2) {
			const Point& first = contour.points.front();

			const Point& last = contour.points.back();

			if (first.x != last.x || first.y != last.y) {
				writeMove(out, first);
			}
		}
	}

	writeFooter(out);

	out.flush();

	return out.good();
}
